routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CatsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('cats', CatsController::class);


Route::get('location_view', function () {
    return view('cats.location'); 
})->name('location_view');

Route::get('get_location_cat', 'App\Http\Controllers\CatsController@getCoords')->name('get_location_cat');

app/Models/Cat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cat extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 
        'price', 
        'name',
        'age',
        'breed',
        'owner_name',
        'description',
        'coords_lat',
        'coords_lng',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CatsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cat;
use Illuminate\Http\Request;

class CatsController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$cats = Cat::all();
	
		return view('cats.index',compact('cats'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('cats.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$request->validate([
			'name' => 'required',
			'age' => 'required|numeric',
			'breed' => 'required',
			'owner_name' => 'required',
			'description' => 'required',
			'coords_lat' => 'required',
			'coords_lng' => 'required',
		]);
	
		$cat = Cat::create($request->all());
	
		return redirect()->route('cats.index')
			->with('success','Cat created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  \App\Models\Cat  $cat
	 * @return \Illuminate\Http\Response
	 */
	public function show(Cat $cat)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \App\Models\Cat  $cat
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Cat $cat)
	{
		//$cat = Cat::findOrFail($id);

		return view('cats.edit', compact('cat'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  \App\Models\Cat  $cat
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$validatedData = $request->validate([
			'name' => 'required',
			'age' => 'required|numeric',
			'breed' => 'required',
			'owner_name' => 'required',
			'description' => 'required',
			'coords_lat' => 'required',
			'coords_lng' => 'required',
		]);

		$update = Cat::whereId($id)->update($validatedData);

		return redirect('/cats')->with('success', 'Cat Data is successfully updated');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  \App\Models\Cat  $cat
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Cat $cat)
	{
		//$cat = Cat::findOrFail($id);
		$cat->delete();

		return redirect('/cats')->with('success', 'Cat Data is successfully deleted');
	}

	public function getCoords(){
		$cats = Cat::all();

		foreach ($cats as $key => $value) {
			$new_array[] = array(
				"type" => "FeatureCollection",
				"features" => array(
					array(
						"type" => "Feature",
						"geometry" => array(
							"type" => "Point",
							"coordinates" => array(
								$value->coords_lng, $value->coords_lat
							)
						),
						"properties" => array(
							"title" => $value->name,
						)
					)
				)
			);
		}

		$new_array = json_decode(json_encode($new_array), true);

		if(!empty($new_array)){
			return response()->json([
					'success' => true,
					'data' => $new_array
			], 200);
		}else{
			return response()->json([
					'error' => true,
					'data' => []
			], 400);
		}
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/cats/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
	<div class="card-header">
		<h2>Add Cat Data</h2>
	</div>
	<div class="card-body">
		@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div><br />
		@endif
			<form method="post" action="{{ route('cats.store') }}">
				<div class="form-group">
					@csrf
					<label for="cat_name">Cat Name:</label>
					<input type="text" class="form-control" name="name"/>
				</div>
				<br>
				<div class="form-group">
					<label for="cases">Age :</label>
					<input type="text" class="form-control" placeholder="In years" name="age"/>
				</div>
				<br>
				<div class="form-group">
					<label for="cases">Breed :</label>
					<input type="text" class="form-control" name="breed"/>
				</div>
				<br>
				<div class="form-group">
					<label for="cases">Owner's name :</label>
					<input type="text" class="form-control" name="owner_name"/>
				</div>
				<br>
				<div class="form-group">
					<label for="cases">Description :</label>
					<input type="text" class="form-control" name="description"/>
				</div>
				<br>
				<div class="form-group">
					<label for="cases">Latitude Coords :</label>
					<input type="text" class="form-control" name="coords_lat"/>
				</div>
				<br>
				<div class="form-group">
					<label for="cases">Longitude Coords :</label>
					<input type="text" class="form-control" name="coords_lng"/>
				</div>
				<br>
				<button type="submit" class="btn btn-primary">Add Cat</button>
			</form>
	</div>
</div>
@endsection

resources/views/cats/edit.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
	<div class="card-header">
		<h2>Edit Cat Data</h2>
	</div>
	<div class="card-body">
		@if ($errors->any())
			<div class="alert alert-danger">
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div><br />
		@endif
		<form method="post" action="{{ route('cats.update', $cat->id ) }}">
			<div class="form-group">
				@csrf
				@method('PATCH')
				<label for="country_name">Cat Name:</label>
				<input type="text" class="form-control" name="name" value="{{ $cat->name }}"/>
			</div>
			<br>
			<div class="form-group">
				<label for="cases">Cat age :</label>
				<input type="text" class="form-control" name="age" value="{{ $cat->age }}"/>
			</div>
			<br>
			<div class="form-group">
				<label for="cases">Breed :</label>
				<input type="text" class="form-control" name="breed" value="{{ $cat->breed }}"/>
			</div>
			<br>
			<div class="form-group">
				<label for="cases">Owner's name :</label>
				<input type="text" class="form-control" name="owner_name" value="{{ $cat->owner_name }}"/>
			</div>
			<br>
			<div class="form-group">
				<label for="cases">Description :</label>
				<input type="text" class="form-control" name="description" value="{{ $cat->description }}"/>
			</div>
			<br>
			<div class="form-group">
				<label for="cases">Latitude Coords :</label>
				<input type="text" class="form-control" name="coords_lat" value="{{ $cat->coords_lat }}"/>
			</div>
			<br>
			<div class="form-group">
				<label for="cases">Longitude Coords :</label>
				<input type="text" class="form-control" name="coords_lng" value="{{ $cat->coords_lng }}"/>
			</div>
			<br>
			<button type="submit" class="btn btn-primary">Update Data</button>
		</form>
	</div>
</div>
@endsection

resources/views/cats/index.blade.php
@extends('layout')

@section('content')


<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <form class="form-inline">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>
  </form>

</nav>
<!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="row">
    <div class="col-md-10">
      <h1 class="h3 mb-2 text-gray-800">Cats management</h1>
    </div>
    <div class="col-md-2">
      <div class="pull-right">
        <a class="btn btn-success" href="{{ route('cats.create') }}"> Create New Cat</a>
      </div>
    </div>
  </div>
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      @if(session()->get('success'))
        <div class="alert alert-success">
          {{ session()->get('success') }}  
        </div>
      @endif
    </div>
    <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>ID</th>
                <th>Cat Name</th>
                <th>Age</th>
                <th>Breed</th>
                <th>Owner's name</th>
                <th>Description</th>
                <th colspan="2">Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($cats as $cat)
                <tr>
                  <td>{{$cat->id}}</td>
                  <td>{{$cat->name}}</td>
                  <td>{{$cat->age}} years</td>
                  <td>{{$cat->breed}}</td>
                  <td>{{$cat->owner_name}}</td>
                  <td>{{$cat->description}}</td>
                  <td><a href="{{ route('cats.edit', $cat->id)}}" class="btn btn-primary">Edit</a></td>
                  <td>
                    <form action="{{ route('cats.destroy', $cat->id)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>
    </div>
  </div>

</div>




@endsection

resources/views/cats/location.blade.php
@extends('layout')

<script src='https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.css' rel='stylesheet' />

<style>
   body {
      margin: 0;
      padding: 0;
   }

   #map {
      top: 0;
      bottom: 0;
      width: 100%;
      height: 500px;
   }
   
   .marker {
      background-image: url('../assets/img/marker2.png');
      background-size: cover;
      width: 50px;
      height: 50px;
      border-radius: 50%;
      cursor: pointer;
   }

   .mapboxgl-popup {
      max-width: 200px;
   }

   .mapboxgl-popup-content {
      text-align: center;
      font-family: 'Open Sans', sans-serif;
   }
</style>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous"></script>
@section('content')

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <form class="form-inline">
      <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
         <i class="fa fa-bars"></i>
      </button>
   </form>

</nav>
<!-- End of Topbar -->

<!-- Begin Page Content -->
<div class="container-fluid">

   <div class="row">
      <h1 class="h3 mb-2 text-gray-800">Cats Locations</h1>
   </div>

   <div class="card-body">
      <div class="row">
         <div class="col-md-12">
            <div id="map"></div>
         </div>
     </div>
   </div>
</div>


@endsection

<script>
   mapboxgl.accessToken = 'pk.eyJ1IjoiamNvcmVhczk0IiwiYSI6ImNsMGoycHVqOTA4aXQzanI1czNta3B0eGIifQ.s7QMkNotKRhHwZ7SjfecDw';

   $( document ).ready(function() {
      $.ajax({
         url:"{{ route('get_location_cat') }}",
         //type:"GET",
         success:function(response){
            if(response.success){
               console.log(response.data);
               geojson = response.data;

               var map = new mapboxgl.Map({
                  container: 'map',
                  style: 'mapbox://styles/mapbox/light-v10',
                  center: [-89.1090687,13.7154416],
                  zoom: 14
               });

               $.each(geojson, function (key, val) {

                  val.features.forEach(function (marker) {
                     // create a HTML element for each feature
                     var el = document.createElement('div');
                     el.className = 'marker';

                     // make a marker for each feature and add it to the map
                     new mapboxgl.Marker(el)
                     .setLngLat(marker.geometry.coordinates)
                     .setPopup(
                        new mapboxgl.Popup({ offset: 10 }) // add popups
                        .setHTML(
                           '<h4>Name </h4><span>' +
                           marker.properties.title +
                           '</span>'
                        )
                     )
                     .addTo(map);
                  });
               });
            }
         }
      });
   });

</script>

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Challenge 1 - Cats Management</title>
  <!-- Custom fonts for this template -->
  
	<link href="{{ asset('assets/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
	<link
		href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="{{ asset('assets/css/sb-admin-2.min.css') }}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
	<div id="wrapper">

		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

			<!-- Sidebar - Brand -->
			<a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
				<div class="sidebar-brand-icon rotate-n-15">
					<i class="fas fa-cat"></i>
				</div>
				<div class="sidebar-brand-text mx-3">Cats</div>
			</a>

			<!-- Divider -->
			<hr class="sidebar-divider my-0">

			<!-- Nav Item - Tables -->
			<li class="nav-item active">
				<a class="nav-link" href="{{ route('cats.index')}}">
					<i class="fas fa-fw fa-table"></i>
					<span>Management</span>
				</a>
			</li>

			<!-- Nav Item - Dashboard -->
			<li class="nav-item">
				<a class="nav-link" href="{{ route('location_view')}}">
					<i class="fas fa-map-marked-alt"></i>
					<span>Location</span>
				</a>
			</li>
		</ul>
		<!-- End of Sidebar -->

		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">
        @yield('content')
      </div>
			<!-- End of Main Content -->

			<!-- Footer -->
			<footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Challenge 1 - Cats Management</span>
          </div>
        </div>
			</footer>
			<!-- End of Footer -->

		</div>
		<!-- End of Content Wrapper -->
	</div>


  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
  <!-- Bootstrap core JavaScript-->
	<script src="{{ asset('assets/vendor/jquery/jquery.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

	<!-- Core plugin JavaScript-->
	<script src="{{ asset('assets/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

	<!-- Custom scripts for all pages-->
	<script src="{{ asset('assets/js/sb-admin-2.min.js') }}"></script>

</body>

</html>